# SEO Audit Tool Configuration v2.0
environment: development
version: "2.0.0"
secret_key: "dev-secret-key-12345"

# Server Configuration
host: "0.0.0.0"
port: 10000

# Features
serp_analysis_enabled: true
advanced_crawling_enabled: true
admin_endpoints_enabled: true
caching_enabled: true
rate_limiting_enabled: false

# Crawling settings
max_pages_limit: 987
max_concurrent_requests: 2
request_delay: 1.5
request_timeout: 30
respect_robots_txt: true

# Analysis settings
min_word_count: 50
max_title_length: 60
min_title_length: 5
max_meta_description_length: 160
min_meta_description_length: 30

# Directories
reports_dir: "reports"
exports_dir: "exports"
logs_dir: "logs"

# Logging
log_level: "INFO"
log_to_file: true

# Performance
cache_ttl: 3600
max_concurrent_analyses: 3
max_report_size: 10485760

# Security
allowed_origins: "*"
cors_enabled: true
trusted_proxies:
  - "127.0.0.1"
  - "::1"
