
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: seo-audit-tool
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/timeout: "900"  # 15 minutes
    spec:
      containerConcurrency: 10
      timeoutSeconds: 900
      containers:
      - image: gcr.io/PROJECT_ID/seo-audit-tool
        ports:
        - containerPort: 8080
        env:
        - name: ZENSERP_API_KEY
          valueFrom:
            secretKeyRef:
              name: zenserp-api-key
              key: api-key
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: secret-key
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
