services:
  - type: web
    name: seo-audit-service
    env: python
    region: us-central1
    plan: free
    runtime: python-3.11
    buildCommand: |
      python --version
      echo "Current Python version check..."
      if python --version | grep -q "3.13"; then
        echo "ERROR: Python 3.13 detected - this will cause build failures"
        echo "Please ensure Python 3.11 is being used"
        exit 1
      fi
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app --workers 2 --timeout 120 --preload
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MAX_CONCURRENT_REQUESTS
        value: 3
      - key: REQUEST_TIMEOUT
        value: 30
      - key: CACHE_ENABLED
        value: true
      - key: SERP_ANALYSIS_ENABLED
        value: true
      - key: RATE_LIMIT_REQUESTS
        value: 5
      - key: RATE_LIMIT_WINDOW
        value: 60
      - key: MAX_PAGES_LIMIT
        value: 50
      - key: WHOLE_WEBSITE_MAX_PAGES
        value: 500
      - key: PYTHON_VERSION
        value: "3.11"
    healthCheckPath: /api/health
